In [1]:
from time import time
import csv
import pandas as pd
import numpy as np
from sklearn import preprocessing
from sklearn.naive_bayes import MultinomialNB
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.feature_extraction.text import HashingVectorizer
from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_val_score
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import AdaBoostClassifier
from xgboost import XGBClassifier
from sklearn import tree
from sklearn.model_selection import GridSearchCV
from sklearn import metrics
from sklearn.svm import SVC
import matplotlib.pyplot as plt
from sklearn.cluster import KMeans
import nltk
from nltk.stem.porter import PorterStemmer
from nltk.stem.snowball import SnowballStemmer

data = pd.read_csv('train.csv', sep=',', header=None)
test = pd.read_csv('test.csv', sep=',', header=None)

labels = data[2]
le = preprocessing.LabelEncoder()
y_train = le.fit_transform(labels)
print (le.classes_)
print (le.transform(le.classes_))


train_text = list(data[1])
test_text = list(test[1])

def parseOutText(f):
    content = f

    words = ""
    if len(content) > 1:
        stemmer = SnowballStemmer("english")
        split = content.split()  
        text = [stemmer.stem(word) for word in split]
        words = ' '.join(text)
        
    return words

X_train = []
for sentence in train_text:
    stemmed_sentence = parseOutText(sentence)
    X_train.append(stemmed_sentence)
X_test = []
for sentencee in test_text:
    stemmed_sentencee = parseOutText(sentencee)
    X_test.append(stemmed_sentencee)

print (len(X_train))
print (len(y_train))
print (len(X_test))
print (X_train[:2])
print (X_test[:2])

tfidff = TfidfVectorizer(max_df=0.4)
print (tfidff)

t_train_text = tfidff.fit_transform(X_train)

t_test_test = tfidff.transform(X_test)

tfidff.vocabulary_.__len__()

clfmnb = MultinomialNB(alpha=0.02)
clfmnb.fit(t_train_text, y_train)

predicted = clfmnb.predict_proba(t_test_test)

pred = clfmnb.predict(t_test_test)

print (pred[:10])



['EAP' 'HPL' 'MWS']
[0 1 2]
19579
19579
8392
['this process, however, afford me no mean of ascertain the dimens of my dungeon; as i might make it circuit, and return to the point whenc i set out, without be awar of the fact; so perfect uniform seem the wall.', 'it never onc occur to me that the fumbl might be a mere mistake.']
['still, as i urg our leav ireland with such inquietud and impatience, my father thought it best to yield.', 'if a fire want fanning, it could readili be fan with a newspaper, and as the govern grew weaker, i have no doubt that leather and iron acquir durabl in proportion, for, in a veri short time, there was not a pair of bellow in all rotterdam that ever stood in need of a stitch or requir the assist of a hammer.']
TfidfVectorizer(analyzer='word', binary=False, decode_error='strict',
        dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
        lowercase=True, max_df=0.4, max_features=None, min_df=1,
        ngram_range=(1, 1), norm='l2', prep

In [4]:
pred = le.inverse_transform(pred)

In [5]:
print (pred[:10])

['MWS' 'EAP' 'HPL' 'EAP' 'EAP' 'EAP' 'EAP' 'MWS' 'EAP' 'EAP']


In [6]:
data_id = pd.DataFrame(test[0])
data_text = pd.DataFrame(test[1])
pred = pd.DataFrame(pred)

data_text = data_text.rename(columns={0:'text'})
pred = pred.rename(columns={0:'author'})
data_id = data_id.rename(columns={0:'id'})

output = pd.concat([data_id,data_text,pred],axis=1)

output.to_csv('output_with_author.csv', sep=',', index=False)
print ('done')

done


In [ ]:
data_id = pd.DataFrame(test[0])
pred_proba = pd.DataFrame(predicted)

pred_proba = pred_proba.rename(columns={0:'EAP',1:'HPL',2:'MWS'})
data_id = data_id.rename(columns={0:'id'})

output = pd.concat([data_id,pred_proba],axis=1)

output.to_csv('submission.csv', sep=',', index=False)
print ('done')

In [4]:
from time import time
import csv
import pandas as pd
import numpy as np
from sklearn import preprocessing
from sklearn.naive_bayes import MultinomialNB
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.feature_extraction.text import HashingVectorizer
from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_val_score
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import AdaBoostClassifier
from xgboost import XGBClassifier
from sklearn import tree
from sklearn.model_selection import GridSearchCV
from sklearn import metrics
from sklearn.svm import SVC
import matplotlib.pyplot as plt
from sklearn.cluster import KMeans
import nltk
from nltk.stem.porter import PorterStemmer
from nltk.stem.snowball import SnowballStemmer
from nltk.stem.wordnet import WordNetLemmatizer
from nltk.corpus import wordnet
nltk.download('wordnet')

train_file = pd.read_csv('train.csv', sep=',', header=None)
test_file = pd.read_csv('test.csv', sep=',', header=None)

X = list(train_file[1])
X_test = list(test_file[1])


[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\cpads\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!


In [5]:
labels = train_file[2]
le = preprocessing.LabelEncoder()
y = le.fit_transform(labels)

lem = WordNetLemmatizer()
print (lem.lemmatize('car'))

def parseOutText(f):
    content = f

    words = ""
    if len(content) > 1:
        lem = WordNetLemmatizer()
        split = content.split()  
        text = [lem.lemmatize(word) for word in split]
        words = ' '.join(text)
        
    return words

l_X = []
for sentence in X:
    lem_sentence = parseOutText(sentence)
    l_X.append(lem_sentence)

l_Y = []
for s in X_test:
    lems = parseOutText(s)
    l_Y.append(lems)

car


In [9]:
tfidf = TfidfVectorizer(ngram_range=(1,2), max_df=0.4)

t_x_train = tfidf.fit_transform(l_X)

t_x_test = tfidf.transform(l_Y)

mnb = MultinomialNB(alpha=0.06)

mnb.fit(t_x_train, y)

pred = mnb.predict_proba(t_x_test)


In [11]:
data_id2 = pd.DataFrame(test_file[0])

pred_proba2 = pd.DataFrame(pred)

pred_proba2 = pred_proba2.rename(columns={0:'EAP',1:'HPL',2:'MWS'})
data_id2 = data_id2.rename(columns={0:'id'})

output2 = pd.concat([data_id2,pred_proba2],axis=1)

output2.to_csv('submission.csv', sep=',', index=False)
print ('done')

done


In [12]:
#Bekar hai niche wala
from time import time
import csv
import pandas as pd
import numpy as np
from sklearn import preprocessing
from sklearn.naive_bayes import MultinomialNB
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.feature_extraction.text import HashingVectorizer
from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_val_score
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import AdaBoostClassifier
from xgboost import XGBClassifier
from sklearn import tree
from sklearn.model_selection import GridSearchCV
from sklearn import metrics
from sklearn.svm import SVC
import matplotlib.pyplot as plt
from sklearn.cluster import KMeans
import nltk
from nltk.stem.porter import PorterStemmer
from nltk.stem.snowball import SnowballStemmer

data = pd.read_csv('train.csv', sep=',', header=None)
test = pd.read_csv('test.csv', sep=',', header=None)

labels = data[2]
le = preprocessing.LabelEncoder()
y_train = le.fit_transform(labels)
print (le.classes_)
print (le.transform(le.classes_))


train_text = list(data[1])
test_text = list(test[1])

def parseOutText(f):
    content = f

    words = ""
    if len(content) > 1:
        stemmer = PorterStemmer()
        split = content.split()  
        text = [stemmer.stem(word) for word in split]
        words = ' '.join(text)
        
    return words

X_train = []
for sentence in train_text:
    stemmed_sentence = parseOutText(sentence)
    X_train.append(stemmed_sentence)
X_test = []
for sentencee in test_text:
    stemmed_sentencee = parseOutText(sentencee)
    X_test.append(stemmed_sentencee)

print (len(X_train))
print (len(y_train))
print (len(X_test))
print (X_train[:2])
print (X_test[:2])

tfidff = TfidfVectorizer(max_df=0.4)
print (tfidff)

t_train_text = tfidff.fit_transform(X_train)

t_test_test = tfidff.transform(X_test)

tfidff.vocabulary_.__len__()

clfmnb = MultinomialNB(alpha=0.06)
clfmnb.fit(t_train_text, y_train)

predicted = clfmnb.predict_proba(t_test_test)

print (predicted[:10])


['EAP' 'HPL' 'MWS']
[0 1 2]
19579
19579
8392
['thi process, however, afford me no mean of ascertain the dimens of my dungeon; as I might make it circuit, and return to the point whenc I set out, without be awar of the fact; so perfectli uniform seem the wall.', 'It never onc occur to me that the fumbl might be a mere mistake.']
['still, as I urg our leav ireland with such inquietud and impatience, my father thought it best to yield.', 'If a fire want fanning, it could readili be fan with a newspaper, and as the govern grew weaker, I have no doubt that leather and iron acquir durabl in proportion, for, in a veri short time, there wa not a pair of bellow in all rotterdam that ever stood in need of a stitch or requir the assist of a hammer.']
TfidfVectorizer(analyzer='word', binary=False, decode_error='strict',
        dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
        lowercase=True, max_df=0.4, max_features=None, min_df=1,
        ngram_range=(1, 1), norm='l2', prep

In [13]:
data_id = pd.DataFrame(test[0])
pred_proba = pd.DataFrame(predicted)

pred_proba = pred_proba.rename(columns={0:'EAP',1:'HPL',2:'MWS'})
data_id = data_id.rename(columns={0:'id'})

output = pd.concat([data_id,pred_proba],axis=1)

output.to_csv('submission.csv', sep=',', index=False)
print ('done')

done


In [16]:
from time import time
import csv
import pandas as pd
import numpy as np
from sklearn import preprocessing
from sklearn.naive_bayes import MultinomialNB
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.feature_extraction.text import HashingVectorizer
from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_val_score
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import AdaBoostClassifier
from xgboost import XGBClassifier
from sklearn import tree
from sklearn.model_selection import GridSearchCV
from sklearn import metrics
from sklearn.svm import SVC
import matplotlib.pyplot as plt
from sklearn.cluster import KMeans
import nltk
from nltk.stem.porter import PorterStemmer
from nltk.stem.snowball import SnowballStemmer
from sklearn import linear_model

data = pd.read_csv('train.csv', sep=',', header=None)
test = pd.read_csv('test.csv', sep=',', header=None)

labels = data[2]
le = preprocessing.LabelEncoder()
y_train = le.fit_transform(labels)
print (le.classes_)
print (le.transform(le.classes_))


train_text = list(data[1])
test_text = list(test[1])

def parseOutText(f):
    content = f

    words = ""
    if len(content) > 1:
        stemmer = SnowballStemmer("english")
        split = content.split()  
        text = [stemmer.stem(word) for word in split]
        words = ' '.join(text)
        
    return words

X_train = []
for sentence in train_text:
    stemmed_sentence = parseOutText(sentence)
    X_train.append(stemmed_sentence)
X_test = []
for sentencee in test_text:
    stemmed_sentencee = parseOutText(sentencee)
    X_test.append(stemmed_sentencee)

print (len(X_train))
print (len(y_train))
print (len(X_test))
print (X_train[:2])
print (X_test[:2])

tfidff = TfidfVectorizer(ngram_range=(1,2), max_df=0.4)
print (tfidff)

t_train_text = tfidff.fit_transform(X_train)

t_test_test = tfidff.transform(X_test)

tfidff.vocabulary_.__len__()

clfsd = linear_model.SGDClassifier(penalty='l2', alpha=0.0001, loss='modified_huber', l1_ratio=0.5, epsilon=0.1)
clfsd.fit(t_train_text, y_train)

clfsd_pred = clfsd.predict_proba(t_test_test)

print (clfsd_pred[:10])

['EAP' 'HPL' 'MWS']
[0 1 2]
19579
19579
8392
['this process, however, afford me no mean of ascertain the dimens of my dungeon; as i might make it circuit, and return to the point whenc i set out, without be awar of the fact; so perfect uniform seem the wall.', 'it never onc occur to me that the fumbl might be a mere mistake.']
['still, as i urg our leav ireland with such inquietud and impatience, my father thought it best to yield.', 'if a fire want fanning, it could readili be fan with a newspaper, and as the govern grew weaker, i have no doubt that leather and iron acquir durabl in proportion, for, in a veri short time, there was not a pair of bellow in all rotterdam that ever stood in need of a stitch or requir the assist of a hammer.']
TfidfVectorizer(analyzer='word', binary=False, decode_error='strict',
        dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
        lowercase=True, max_df=0.4, max_features=None, min_df=1,
        ngram_range=(1, 2), norm='l2', prep

In [17]:
data_id = pd.DataFrame(test[0])
pred_proba = pd.DataFrame(clfsd_pred)

pred_proba = pred_proba.rename(columns={0:'EAP',1:'HPL',2:'MWS'})
data_id = data_id.rename(columns={0:'id'})

output = pd.concat([data_id,pred_proba],axis=1)

output.to_csv('submission.csv', sep=',', index=False)
print ('done')

done
