In [1]:
import csv
import pandas as pd
import numpy as np
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.ensemble import RandomForestClassifier
from sklearn import preprocessing

In [2]:
train_data = pd.read_csv("train.csv", sep=",", header=None)
test_data = pd.read_csv("test.csv", sep=",", header=None)

In [3]:
X_train = train_data[1]
labels_name = train_data[2]
X_test = test_data[1]

In [4]:
le = preprocessing.LabelEncoder()
le.fit(labels_name)
list(le.classes_)

['EAP', 'HPL', 'MWS']

In [5]:
y_train = le.transform(labels_name)

In [6]:
tfidf_clf = TfidfVectorizer()
t_X_train = tfidf_clf.fit_transform(X_train)
t_X_test = tfidf_clf.transform(X_test)

In [11]:
clf_rf = RandomForestClassifier(n_jobs=-1, n_estimators=1000)

In [12]:
clf_rf.fit(t_X_train, y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_split=1e-07, min_samples_leaf=1,
            min_samples_split=2, min_weight_fraction_leaf=0.0,
            n_estimators=1000, n_jobs=-1, oob_score=False,
            random_state=None, verbose=0, warm_start=False)

In [13]:
rf_pred = clf_rf.predict_proba(t_X_test)

In [14]:
print (rf_pred)

[[ 0.28   0.113  0.607]
 [ 0.601  0.278  0.121]
 [ 0.188  0.667  0.145]
 ..., 
 [ 0.751  0.141  0.108]
 [ 0.427  0.172  0.401]
 [ 0.435  0.471  0.094]]


In [145]:
text_id = pd.DataFrame(test_data[0])

In [147]:
proba = pd.DataFrame(rf_pred)

In [149]:
proba = proba.rename(columns={0:'EAP',1:'HPL',2:'MWS'})
text_id = text_id.rename(columns={0:'id'})

In [153]:
output = pd.concat([text_id,proba],axis=1)

In [162]:
output.to_csv('submission.csv', sep=',', index=False)